### ISSUE TITLE
Change required flieds for POST-request

### ISSUE THREAD

**Issue by MaxymVlasov** [itkpi/events-public#2]
for /api/v1/suggested_events
- [ ] when_end - NOT required flied 
- [ ]  registration_url - NOT required flied

**Comment by rrader** [comment]
да ты издеваешься :smile: 

when_end is already not required.
registration_url is required as per #1 . Are you sure we need to change this?

**Comment by MaxymVlasov** [comment]
@rrader ноуп)

You told me, that 'Suggest Events form' and 'suggest api' are not associated among ourselves.

**Comment by MaxymVlasov** [comment]
No longer relevant.
