### ISSUE TITLE
Don't work URL /events/suggest 

### ISSUE THREAD

**Issue by MaxymVlasov** [itkpi/events-public#3]
Той старий баг, на який ми підзабили.
Суть в чому: http://itkpi.pp.ua/events/suggest/ працює, 
А http://itkpi.pp.ua/events/suggest - ні.

**Comment by rrader** [comment]
это не баг, зачем это фиксить? почему оно должно работать?

**Comment by webknjaz** [comment]
WAT?

**Comment by MaxymVlasov** [comment]
@rrader  Якщо це не баг, то що це?
Всюди конструкції `/blabla` і `/blavla/` працюють однаково, чому вони  в `suggest` має себе по іншому вести?

**Comment by rrader** [comment]
Потому что это разные урлы. Оно работает потому что настроен редирект, но для post запроса нельзя делать редирект

**Comment by MaxymVlasov** [comment]
А через [HTTP 303](https://en.wikipedia.org/wiki/HTTP_303) ніяк?

**Comment by rrader** [comment]
POST нельзя редиректить
http://www.alanflavell.org.uk/www/post-redirect.html

**Comment by MaxymVlasov** [comment]
No longer relevant.
